from .user import User
from .game import Game
from .categoria import Categoria
from .game_categoria import GameCategoria
from .avaliacao import Avaliacao
from .historico_preco import HistoricoPreco
from .jogos_monitorados import JogosMonitorados
from .game_plataforma import GamePlataforma
from .plataforma import Plataforma
